CARDAINATION-UPDATED/cardination/doctor/routes.py
from flask import render_template, url_for, flash, redirect, request , Blueprint
from cardination.doctor.forms import RegisterDoc
from cardination.patient.forms import LoginForm 
from cardination.models import Patient, Doctor, User
from cardination import db, bcrypt
from flask_login import login_user, current_user, login_required,logout_user

doctor = Blueprint('doctor',__name__)

@doctor.route("/registerDoc", methods=['GET', 'POST'])
def registerDoc():
    form = RegisterDoc()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User()
        db.session.add(user)
        db.session.commit()
        doctor = Doctor(id = user.id, username = form.username.data,email = form.email.data,password=hashed_password,specialization=form.specialization.data,degree=form.degree.data,phone_number=form.phonenumber.data,address=form.address.data)
        db.session.add(doctor)
        db.session.commit()
        flash(f'Account created for {form.username.data}!', 'success')
        return redirect(url_for('doctor.loginDoc'))
    return render_template('registerDoc.html', title='Register Doctor', form=form)

@doctor.route("/loginDoc", methods=['GET', 'POST'])
def loginDoc():
    form = LoginForm()
    if form.validate_on_submit():
        doctor = Doctor.query.filter_by(email = form.email.data).first()
        if doctor and bcrypt.check_password_hash(doctor.password,form.password.data):
            user = doctor.user
            login_user(user,remember = form.remember.data)
            return redirect(url_for('doctor.accountDoc'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('loginDoc.html', title='Login Doctor', form=form)

@doctor.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("main.home"))

@doctor.route("/accountDoc")
@login_required
def accountDoc():
    doc = Doctor.query.filter_by(id=current_user.id).first()
    if doc:
        image_file=url_for('static',filename='profile_pic/'+Doctor.query.filter_by(id=current_user.id).first().image_file)
        return render_template('accountDoc.html',image_file=image_file, doc=doc)
    else:
        return redirect(url_for('doctor.logout'))

CARDAINATION-UPDATED/cardination/main/routes.py
from flask import Blueprint,render_template

main = Blueprint('main',__name__)

@main.route('/')
@main.route('/home')
def home():
    return render_template("home.html")

CARDAINATION-UPDATED/cardination/patient/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from cardination.patient.forms import RegistrationForm, LoginForm 
from cardination.models import Patient, Doctor, User
from cardination import db, bcrypt
from flask_login import login_user, current_user, logout_user, login_required

patient = Blueprint('patient',__name__)

@patient.route("/registerPatient", methods=['GET', 'POST'])
def registerPatient():
    global boolean
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User()
        db.session.add(user)
        db.session.commit()
        patient = Patient(id = user.id, username = form.username.data,email = form.email.data,password=hashed_password,weight=form.weight.data,height=form.height.data,gender=form.gender.data,bloodgroup=form.bloodgroup.data,dob=request.form.get('DOB'))
        db.session.add(patient)
        db.session.commit()
        flash(f'Account created for {form.username.data}, Now you can login!', 'success')
        return redirect(url_for('patient.loginPatient'))
    return render_template('registerPatient.html', title='Register Patient', form=form)

@patient.route("/loginPatient", methods=['GET', 'POST'])
def loginPatient():
    if current_user.is_authenticated:
        return redirect(url_for('patient.accountPat'))
    form = LoginForm()
    if form.validate_on_submit():
        patient = Patient.query.filter_by(email = form.email.data).first()
        if patient and bcrypt.check_password_hash(patient.password,form.password.data):
            user = patient.user
            login_user(user,remember = form.remember.data)
            return redirect(url_for('patient.accountPat'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('loginPatient.html', title='Login Patient', form=form)

@patient.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("main.home"))

@patient.route("/accountPat")
@login_required
def accountPat():
    pat = Patient.query.filter_by(id=current_user.id).first()
    if pat:
        image_file=url_for('static',filename='profile_pic/'+ Patient.query.filter_by(id=current_user.id).first().image_file)
        return render_template('accountPat.html',image_file=image_file, pat=pat)
    else:
        return redirect(url_for('patient.logout'))



CARDAINATION-UPDATED/cardination/templates/accountDoc.html
{% extends "layoutDoc.html" %}

{% block head %}
<style>
    
body{
    background: -webkit-linear-gradient(left, #3931af, #00c6ff);
}
.emp-profile{
    padding: 3%;
    margin-top: 3%;
    margin-bottom: 3%;
    border-radius: 0.5rem;
    background: #fff;
}
.profile-img{
    text-align: center;
}
.profile-img img{
    width: 60%;
    height: 100%;
}
.profile-img .file {
    position: relative;
    overflow: hidden;
    margin-top: -20%;
    width: 60%;
    border: none;
    border-radius: 0;
    font-size: 15px;
    background: #212529b8;
}
.profile-img .file input {
    position: absolute;
    opacity: 0;
    right: 0;
    top: 0;
}
.profile-head h5{
    color: #333;
}
.profile-head h6{
    color: #0062cc;
}
.profile-edit-btn{
    border: none;
    border-radius: 1.5rem;
    width: 70%;
    padding: 2%;
    font-weight: 600;
    color: #6c757d;
    cursor: pointer;
}
.proile-rating{
    font-size: 12px;
    color: #818182;
    margin-top: 5%;
}
.proile-rating span{
    color: #495057;
    font-size: 15px;
    font-weight: 600;
}
.profile-head .nav-tabs{
    margin-bottom:5%;
}
.profile-head .nav-tabs .nav-link{
    font-weight:600;
    border: none;
}
.profile-head .nav-tabs .nav-link.active{
    border: none;
    border-bottom:2px solid #0062cc;
}
.profile-work{
    padding: 14%;
    margin-top: -15%;
}
.profile-work p{
    font-size: 12px;
    color: #818182;
    font-weight: 600;
    margin-top: 10%;
}
.profile-work a{
    text-decoration: none;
    color: #495057;
    font-weight: 600;
    font-size: 14px;
}
.profile-work ul{
    list-style: none;
}
.profile-tab label{
    font-weight: 600;
}
.profile-tab p{
    font-weight: 600;
    color: #0062cc;
}
</style>
{% endblock %}
{% block content %}


<div class="container emp-profile">
<form method="post">
<div class="row">
    <div class="col-md-4">
        <div class="profile-img">
            <img src="{{ image_file }}" alt=""/>
            <div class="file btn btn-lg btn-primary">
                Change Photo
                <input type="file" name="file"/>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="profile-head">
                    <h5>
                        {{ doc.username }}
                    </h5>
            <ul class="nav nav-tabs" id="myTab" role="tablist">
                <li class="nav-item">
                    <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">About</a>
                </li>
            </ul>
        </div>
    </div>
    <div class="col-md-2">
        <input type="submit" class="profile-edit-btn" name="btnAddMore" value="Edit Profile"/>
    </div>
</div>
<div class="row">
    <div class="col-md-8">
        <div style="margin-left:190px;" class="tab-content profile-tab" id="myTabContent">
            <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">          
                <div class="row">
                            <div class="col-md-6">
                                <label>Email</label>
                            </div>
                            <div class="col-md-6">
                                <p>{{ doc.email }}</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Specialization</label>
                            </div>
                            <div class="col-md-6">
                                <p>{{ doc.specialization }}</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Degree</label>
                            </div>
                            <div class="col-md-6">
                                <p>{{ doc.degree }}</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Phone Number</label>
                            </div>
                            <div class="col-md-6">
                                <p>{{ doc.phone_number }}</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Address</label>
                            </div>
                            <div class="col-md-6">
                                <p>{{ doc.address }}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
       


{% endblock content %}

CARDAINATION-UPDATED/cardination/templates/accountPat.html
{% extends "layout.html" %}

{% block head %}
<style>
    
body{
    background: -webkit-linear-gradient(left, #3931af, #00c6ff);
}
.emp-profile{
    padding: 3%;
    margin-top: 3%;
    margin-bottom: 3%;
    border-radius: 0.5rem;
    background: #fff;
}
.profile-img{
    text-align: center;
}
.profile-img img{
    width: 60%;
    height: 100%;
}
.profile-img .file {
    position: relative;
    overflow: hidden;
    margin-top: -20%;
    width: 60%;
    border: none;
    border-radius: 0;
    font-size: 15px;
    background: #212529b8;
}
.profile-img .file input {
    position: absolute;
    opacity: 0;
    right: 0;
    top: 0;
}
.profile-head h5{
    color: #333;
}
.profile-head h6{
    color: #0062cc;
}
.profile-edit-btn{
    border: none;
    border-radius: 1.5rem;
    width: 70%;
    padding: 2%;
    font-weight: 600;
    color: #6c757d;
    cursor: pointer;
}
.proile-rating{
    font-size: 12px;
    color: #818182;
    margin-top: 5%;
}
.proile-rating span{
    color: #495057;
    font-size: 15px;
    font-weight: 600;
}
.profile-head .nav-tabs{
    margin-bottom:5%;
}
.profile-head .nav-tabs .nav-link{
    font-weight:600;
    border: none;
}
.profile-head .nav-tabs .nav-link.active{
    border: none;
    border-bottom:2px solid #0062cc;
}
.profile-work{
    padding: 14%;
    margin-top: -15%;
}
.profile-work p{
    font-size: 12px;
    color: #818182;
    font-weight: 600;
    margin-top: 10%;
}
.profile-work a{
    text-decoration: none;
    color: #495057;
    font-weight: 600;
    font-size: 14px;
}
.profile-work ul{
    list-style: none;
}
.profile-tab label{
    font-weight: 600;
}
.profile-tab p{
    font-weight: 600;
    color: #0062cc;
}
</style>
{% endblock %}
{% block content %}


<div class="container emp-profile">
<div class="row">
    <div class="col-md-4">
        <div class="profile-img">
            <img src="{{ image_file }}" alt="Profile picture">
            <div class="file btn btn-lg btn-primary">
                Change Photo
                <input type="file" name="file"/>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="profile-head">
                    <h5>
                        {{ pat.username }}
                    </h5>
                    
                    
            <ul class="nav nav-tabs" id="myTab" role="tablist">
                <li class="nav-item">
                    <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">About</a>
                </li>
            </ul>
        </div>
    </div>
    <div class="col-md-2">
        <input type="submit" class="profile-edit-btn" name="btnAddMore" value="Edit Profile"/>
    </div>
</div>
<div class="row">
    <div class="col-md-8">
        <div style="margin-left:190px;" class="tab-content profile-tab" id="myTabContent">
            <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">     
                        <div class="row">
                            <div class="col-md-6">
                                <label>Email</label>
                            </div>
                            <div class="col-md-6">
                                <p>{{ pat.email }}</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Height</label>
                            </div>
                            <div class="col-md-6">
                                <p>{{ pat.height }} cms</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Weight</label>
                            </div>
                            <div class="col-md-6">
                                <p>{{ pat.weight }} kgs</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Gender</label>
                            </div>
                            <div class="col-md-6">
                                <p>{{ pat.gender }}</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Blood Group</label>
                            </div>
                            <div class="col-md-6">
                                <p>{{ pat.bloodgroup }}</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Date Of Birth</label>
                            </div>
                            <div class="col-md-6">
                                <p>{{ pat.dob }}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
       


{% endblock content %}

CARDAINATION-UPDATED/cardination/templates/home.html
{% extends "layout.html" %}
{% block content %}
{% endblock content %}

CARDAINATION-UPDATED/cardination/templates/layout.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
 
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel='stylesheet' href='https://use.fontawesome.com/releases/v5.7.0/css/all.css' integrity='sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ' crossorigin='anonymous'>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>  
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% block head %}{% endblock %}
    {% if title %}
        <title>Cardination - {{ title }}</title>
    {% else %}
        <title>Cardination</title>
    {% endif %}

</head>
<body>
        <header class="site-header">
                <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top" style="background-color: rgb(3, 26, 61);">
                  <div class="container">
                    <a class="navbar-brand mr-4" href="/">CARDINATION</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                      <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarToggle">
                      <div class="navbar-nav mr-auto">
                        
                        {% if current_user.is_authenticated %}
                        <a href="{{ url_for('patient.accountPat') }}" class="nav-item nav-link">Account Details</a>
                        <a href="{{ url_for('patient.logout') }}" class="nav-item nav-link">Sign Out</a>

                        {% else %}
                        <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
                        <a class="nav-item nav-link" href="{{ url_for('patient.loginPatient') }}">Patient</a>
                        <a class="nav-item nav-link" href="{{ url_for('doctor.loginDoc') }}">Doctor</a>
                        {% endif %}

                      </div>
                    </div>
                  </div>
                </nav>
              </header>
              
                <div class="container">
                    {% with messages = get_flashed_messages(with_categories=true) %}
                      {% if messages %}
                        {% for category, message in messages %}
                          <div class="alert alert-{{ category }} col-sm-8">
                            {{ message }}
                          </div>
                        {% endfor %}
                      {% endif %}
                    {% endwith %}
                    {% block content %}{% endblock %}

                </div>
</body>
</html>

CARDAINATION-UPDATED/cardination/templates/layoutDoc.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
 
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel='stylesheet' href='https://use.fontawesome.com/releases/v5.7.0/css/all.css' integrity='sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ' crossorigin='anonymous'>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>  
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% block head %}{% endblock %}
    {% if title %}
        <title>Cardination - {{ title }}</title>
    {% else %}
        <title>Cardination</title>
    {% endif %}

</head>
<body>
        <header class="site-header">
                <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top" style="background-color: rgb(3, 26, 61);">
                  <div class="container">
                    <a class="navbar-brand mr-4" href="/">CARDINATION</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                      <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarToggle">
                      <div class="navbar-nav mr-auto">
                        
                        {% if current_user.is_authenticated %}
                        <a href="{{ url_for('doctor.accountDoc') }}" class="nav-item nav-link">Account Details</a>
                        <a href="{{ url_for('doctor.logout') }}" class="nav-item nav-link">Sign Out</a>

                        {% else %}
                        <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
                        <a class="nav-item nav-link" href="{{ url_for('patient.loginPatient') }}">Patient</a>
                        <a class="nav-item nav-link" href="{{ url_for('doctor.loginDoc') }}">Doctor</a>
                        {% endif %}

                      </div>
                    </div>
                  </div>
                </nav>
              </header>
              
                <div class="container">
                    {% with messages = get_flashed_messages(with_categories=true) %}
                      {% if messages %}
                        {% for category, message in messages %}
                          <div class="alert alert-{{ category }} col-sm-8">
                            {{ message }}
                          </div>
                        {% endfor %}
                      {% endif %}
                    {% endwith %}
                    {% block content %}{% endblock %}

                </div>
</body>
</html>

CARDAINATION-UPDATED/cardination/templates/loginDoc.html
{% extends "layout.html" %}
{% block content %}
<div class="col-md-8">
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In - Doctor</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
            <small class="text-muted ml-2">
                <a href="#">Forgot Password?</a>
            </small>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for('doctor.registerDoc') }}">Sign Up Now</a>
        </small>
    </div>
</div>
{% endblock content %}

CARDAINATION-UPDATED/cardination/templates/loginPatient.html
{% extends "layout.html" %}
{% block content %}
<div class="col-md-8">
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In - Patient</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
            <small class="text-muted ml-2">
                <a href="">Forgot Password?</a>
            </small>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for('patient.registerPatient') }}">Sign Up Now</a>
        </small>
    </div>
</div>
{% endblock content %}